### ISSUE TITLE
Needs default args for logger constructor

### ISSUE THREAD

**Issue by jedp** [jedp/node-cef#1]
You should be able to create a new logger with sane, automatic defaults.  This certainly should not happen:

```
> var logger = new cef.Logger()
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at /tmp/node_modules/cef/lib/cef.js:281:16
    at Array.forEach (native)
    at Object.Logger (/tmp/node_modules/cef/lib/cef.js:280:20)
    at repl:1:14
    at REPLServer.eval (repl.js:80:21)
    at repl.js:190:20
    at REPLServer.eval (repl.js:87:5)
    at Interface.<anonymous> (repl.js:182:12)
    at Interface.emit (events.js:67:17)
    at Interface._onLine (readline.js:162:10)
```

**Comment by jedp** [comment]
Resolved in commit @ced01e593
